version: '3.5'

services:
  frontend:
    build: ./frontend
    restart: always

  backend:
    build: ./backend
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - frontend
      - backend
    restart: always
